name: Fetch field from JSON response
on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: set output
      id: set
      run: |
         echo ::set-output name=json_var::'[{ "name": "Suripa Jhonson", "Emp ID": "1" }, { "name": "Pradipta Williams", "Emp ID": "2" }, { "name": "Dhritiman Rathore", "Emp ID": "3" }] '
    - name: use output
      run: |
        echo $json_var | jq '.[].name'
      env:
        json_var: ${{ steps.set.outputs.json_var}}
